MessageList HTML starter code
NSS-Day-Cohort-64/giffylube pull request #29
Opened 2023-05-24 19:33 UTC by sarahsaturday

2023-05-24 20:33 UTC, chesney-hardin requested changes

2023-05-24 20:33 UTC, chesney-hardin commented on scripts/message/PrivateMessages.js
1. make sure you are checking that the message.recipientId===currentUser.userId 
-so you also need to import getCurrentUser from TransientState.js

2. i don't think you need the return in the .filter function? 
- make a new variable for the new array of filtered messages and then iterate over that array with .map

2023-05-24 20:41 UTC, sarahsaturday commented on scripts/message/PrivateMessages.js
gpt says:

The return statement in the .filter function is necessary to indicate whether a message should be included in the filtered array. In this case, we want to return true when the condition is met (message.recipientId === currentUser.userId), indicating that the message should be included.

2023-05-25 14:34 UTC, chesney-hardin requested changes

2023-05-25 15:18 UTC, chesney-hardin approved these changes
yay!

2023-05-25 15:18 UTC, Djmyers1991 approved these changes
I approve you.

2023-05-25 15:18 UTC, merged